name: CI Testing Scraping Workflow Push
on:
  push:
    branches: ["main"]

jobs:
  Code-Scaning:
    runs-on: ubuntu-latest
    steps:
      - name: Bandit scaning
        uses: mdegis/bandit-action@v1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: "."
          level: high
          confidence: high
          exit_zero: true

  Check-Version-Python:
    runs-on: ubuntu-latest
    needs: Code-Scaning
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --no-cache-dir

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

  Testing-Web-Scraping:
    runs-on: ubuntu-latest
    needs: Check-Version-Python
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install library
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt --no-cache-dir
      
      - name: Run Scraping!
        env:
          URL: ${{ secrets.URL }}
        run: |
          python scrap.py